{
 "title": "Complex jsonnet Dashboard",
 "tags": [
  "grizzly",
  "jsonnet",
  "complex"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "25s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode='idle'}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100"
    }
   ]
  }
 ]
}