apiVersion: proxmoxve.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: proxmoxve-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds-proxmox
      namespace: crossplane-system
      key: credentials