apiVersion: v1
kind: Secret
metadata:
  name: example-creds-proxmox
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "pm_api_url": "https://your_endpoint:8006/api2/json",
      "pm_tls_insecure": "true",
      "pm_api_token_id": "api_key_name",
      "pm_api_token_secret": "api_key_value"
    }