apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: testapp-dev
            namespace: testapp-dev
            path: helm/dev
            environment: dev
          - name: testapp-prod
            namespace: testapp-prod
            path: helm/prod
            environment: prod
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: "testapp=core.harbor.domain/test/test-app:~0.0.1,testapp2=core.harbor.domain/test/test-app2:~0.0.1"
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: default
      source:
        repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/gitea_admin/test.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
