---
machine_creds:
  - name: Machine SSH cred Password
    type: Machine
    state: present
    # ssh_key_data: ""  # if you want ssh ujjust add the .pem here
    username: root
    password: root
    org: Default


proxmox_creds:
  - name: Proxmox credentials
    type: "ProxmoxCredentials"
    state: present
    proxmox_url: "https://proxmox-homelab.homelab.com:8006"
    proxmox_user: readonly_user@pve
    proxmox_password: readonly_user
    org: Default