version: '3'

tasks:
  default:
    desc: "Eexcute all tasks in order (no delete cluster)"
    cmds:
      - task create_cluster
      - task apply_kubernetes
      - task deploy_tilt
  create_cluster:
    desc: "Create Kind cluster"
    cmds:
      - kind create cluster  --config hack/kind/cluster.yaml 
  apply_kubernetes: 
    desc: "Apply kubernetes resources"
    cmds:
      - kubectl apply -f k8s/
  deploy_tilt:
    desc: "Dpeploy Tilt"
    cmds:
      - tilt up
  run_tests:
    desc: "Execute Flask tests"
    cmds:
      - python3 -m unittest test_app.py
  delete_cluster:
    desc: "Delete Kind cluster"
    cmds:
      - kind delete cluster