apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/valkiriaaquatica/my_random_things.git
    path: argocd/apps_of_apps/metallb
    targetRevision: main
  destination:
    namespace: metallb-system
    name: test-k3s-context
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true