

- name: Charge credentials variables for Credentials
  include_vars:
    file: credential_vars.yml
  run_once: true

- name: Add Machine credentials for SSH
  awx.awx.credential:
    name: "{{ item.name }}"
    organization: "{{ item.org }}"
    description: Added from AWX Caasc
    credential_type: "{{ item.type }}"
    state: "{{ item.state }}"
    inputs:
      username: "{{ item.username }}"
      password: "{{ item.password }}"
    validate_certs: true
  loop: "{{ machine_creds }}"


- name: Add Proxmox credentials
  awx.awx.credential:
    name: "{{ item.name }}"
    organization: "{{ item.org }}"
    description: Added from AWX Caasc
    credential_type: "{{ item.type }}"
    state: "{{ item.state }}"
    inputs:
      url: "{{ item.proxmox_url }}"
      user: "{{ item.proxmox_user }}"
      password: "{{ item.proxmox_password }}"
    validate_certs: true
  loop: "{{ proxmox_creds }}"

