---
 # this and the LDAP one, i dont use external variables 
- name: Create credential type for Proxmox
  awx.awx.credential_type:
    name: "ProxmoxCredentials"
    description: "Credentials used in inventory in Proxmox and AWX"
    kind: cloud
    inputs:
      fields:
        - id: url
          type: string
          label: URL
        - id: user
          type: string
          label: User
        - id: password
          type: string
          label: Password
          secret: true
      required:
        - url
        - user
        - password
    injectors:   # this is the way you can then pass the variabels as enviroment variables or define as simlpe variables ans the credenitla will used it
      extra_vars:
        proxmox_url: "{{ '{{  url  }}' }}"
        proxmox_user: "{{ '{{ user }}' }}"
        proxmox_password: "{{ '{{ password }}' }}"
      env:
        PROXMOX_URL: "{{ '{{ url }}' }}"
        PROXMOX_USER: "{{ '{{ user }}' }}"
        PROXMOX_PASSWORD: "{{ '{{ password }}' }}"
