- name: Bring inveotires sources variables
  include_vars:
    file: inventories_sources_vars.yaml
  run_once: true

- name: Create inventory source for Proxmox inventory
  awx.awx.inventory_source:
    name: "{{ item.name }}"
    inventory: "{{ item.inventory }}"
    source: "{{ item.source }}"
    source_project: "{{ item.source_project }}"
    source_path: "{{ item.source_path }}"
    overwrite: "{{ item.overwrite }}"
    state: "{{ item.state }}"
    credential: "{{ item.credential }}"
    execution_environment: "{{ item.execution_environment }}"
  loop: "{{ proxmox_inventory_vars }}"

# - name: Update inventory sources to get the latest data  # in case u want to update the inventory and get the hosts
#   awx.awx.inventory_source_update:
#     name: "{{ item.name }}"
#     inventory: "{{ item.inventory }}"
#     organization: "{{ item.organization }}"
#   loop: "{{ proxmox_inventory_vars }}"
#   when: item.state == "present"