apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 'v1.11.0'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    # server: https://rke2-ha.homelab.com:6443
    namespace: cert-manager
    name: test-k3s-context
  syncPolicy:
    automated: {}  # let like this if u want to authomatic sync
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true